-- Seeds for masterdata.mst_employees
-- Generated from sources/employees_mojito360 and sources/employees_kameleonlabs

INSERT INTO masterdata.mst_employees (
    id,
    user_id,
    employee_code,
    first_name,
    last_name,
    email,
    phone,
    hourly_rate,
    hire_date,
    status,
    entity_id,
    department,
    position,
    created_at,
    updated_at,
    created_by,
    updated_by
) VALUES
-- Empleados de Mojito360 S.L.
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%julio%' LIMIT 1),
    'EMP-MOJ-001',
    'Julio',
    'García Martínez',
    'julgarcia@mojito360.com',
    '+34 600 111 222',
    35.00,
    '2022-01-15'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'Mojito360 S.L.' LIMIT 1),
    'Desarrollo',
    'Senior Developer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
-- Empleados de KameleonLabs (primeros 10 para no hacer el seed demasiado largo)
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%adrian%' LIMIT 1),
    'EMP-KLM-001',
    'Adrián',
    'Ávila Morales',
    'adrian@kameleonlabs.ai',
    '+34 600 222 333',
    45.00,
    '2021-06-01'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Dirección',
    'CEO',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%amalia%' LIMIT 1),
    'EMP-KLM-002',
    'Amalia',
    'Jacomino Lorenzo',
    'amalia@kameleonlabs.ai',
    '+34 600 333 444',
    40.00,
    '2021-08-15'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Desarrollo',
    'Senior Developer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%armando%' LIMIT 1),
    'EMP-KLM-003',
    'Armando',
    'Baños Pascual',
    'armando@kameleonlabs.ai',
    '+34 600 444 555',
    38.00,
    '2021-09-01'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Desarrollo',
    'Full Stack Developer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%elias%' LIMIT 1),
    'EMP-KLM-004',
    'Carlos Elías',
    'González Valdés',
    'elias@kameleonlabs.ai',
    '+34 600 555 666',
    42.00,
    '2021-10-01'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Arquitectura',
    'Solutions Architect',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%david%' LIMIT 1),
    'EMP-KLM-005',
    'David',
    'Díaz Martínez',
    'david@kameleonlabs.ai',
    '+34 600 666 777',
    35.00,
    '2021-11-15'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Desarrollo',
    'Backend Developer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%guillermo%' LIMIT 1),
    'EMP-KLM-006',
    'Guillermo',
    'Águila Crespo',
    'guillermo@kameleonlabs.ai',
    '+34 600 777 888',
    37.00,
    '2022-01-01'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Desarrollo',
    'Frontend Developer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%laura%' LIMIT 1),
    'EMP-KLM-007',
    'Laura Elena',
    'Santana Rojas',
    'laura@kameleonlabs.ai',
    '+34 600 888 999',
    36.00,
    '2022-02-01'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Diseño',
    'UX/UI Designer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%luisenrique%' LIMIT 1),
    'EMP-KLM-008',
    'Luis Enrique',
    'Saborit',
    'luisenrique@kameleonlabs.ai',
    '+34 600 999 000',
    39.00,
    '2022-03-15'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Project Management',
    'Project Manager',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%manuel%' LIMIT 1),
    'EMP-KLM-009',
    'Manuel',
    'Quesada Martínez',
    'manuel@kameleonlabs.ai',
    '+34 601 111 222',
    34.00,
    '2022-04-01'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'QA',
    'QA Engineer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%michel%' LIMIT 1),
    'EMP-KLM-010',
    'Michel',
    'Pérez Saavedra',
    'michel@kameleonlabs.ai',
    '+34 601 222 333',
    41.00,
    '2022-05-15'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'DevOps',
    'DevOps Engineer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%nelson%' LIMIT 1),
    'EMP-KLM-011',
    'Nelson',
    'Sánchez Álvarez',
    'nelson@kameleonlabs.ai',
    '+34 601 333 444',
    38.00,
    '2022-06-01'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Desarrollo',
    'Mobile Developer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%osbel%' LIMIT 1),
    'EMP-KLM-012',
    'Osbel',
    'Montero',
    'osbel@kameleonlabs.ai',
    '+34 601 444 555',
    36.00,
    '2022-07-15'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Desarrollo',
    'Junior Developer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%pedro%' LIMIT 1),
    'EMP-KLM-013',
    'Pedro',
    'Romero López',
    'pedro@kameleonlabs.ai',
    '+34 601 555 666',
    43.00,
    '2022-08-01'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Dirección Técnica',
    'CTO',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%rene%' LIMIT 1),
    'EMP-KLM-014',
    'René',
    'Espinosa',
    'rene@kameleonlabs.ai',
    '+34 601 666 777',
    35.00,
    '2022-09-15'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Marketing',
    'Marketing Specialist',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%rogeidis%' LIMIT 1),
    'EMP-KLM-015',
    'Rogeidis',
    'Sifontes Llerena',
    'rogeidis@kameleonlabs.ai',
    '+34 601 777 888',
    37.00,
    '2022-10-01'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Ventas',
    'Sales Representative',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
),
(
    gen_random_uuid(),
    (SELECT id FROM base.mst_users WHERE email LIKE '%thalia%' LIMIT 1),
    'EMP-KLM-016',
    'Thalia',
    'Amos Machado',
    'thalia@kameleonlabs.ai',
    '+34 601 888 999',
    40.00,
    '2022-11-15'::date,
    'activo'::masterdata.employee_status_enum,
    (SELECT id FROM base.mst_entities WHERE name = 'KameleonLabs' LIMIT 1),
    'Desarrollo',
    'Senior Developer',
    NOW(),
    NOW(),
    (SELECT id FROM base.mst_users LIMIT 1),
    (SELECT id FROM base.mst_users LIMIT 1)
)
ON CONFLICT (employee_code) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    hourly_rate = EXCLUDED.hourly_rate,
    updated_at = NOW(),
    updated_by = EXCLUDED.updated_by;
